---
- name: git clone Laradock
  git: repo=https://github.com/Laradock/laradock.git dest=/vagrant/lib/laradock/ version=master

- name: copy Laradock environment file
  copy: src=/vagrant/lib/laradock/env-example dest=/vagrant/lib/laradock/.env

- name: change mysql version
  replace:
    path: /vagrant/lib/laradock/.env
    regexp: 'MYSQL_VERSION=*.*'
    replace: 'MYSQL_VERSION=5.7'
  tags:
    - replace

- name: change project folder
  replace:
    path: /vagrant/lib/laradock/.env
    regexp: 'APP_CODE_PATH_HOST=*.*'
    replace: 'APP_CODE_PATH_HOST=/vagrant/app'
  tags:
    - replace

- name: dokcer compose Laradock(nginx, mysql, phpmyadmin, workspace)
  docker_service:
    state: present
    project_src: /vagrant/lib/laradock
    services:
        - nginx
        - mysql
        - phpmyadmin
        - workspace
  tags:
    - docker
